[functions]
    external_node_modules = ["express"]
    node_bundler = "esbuild"
  
[build]
    functions = "netlify/functions"
    publish = "src/public"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/app"
    status = 200

[[redirects]]
    from = "/"
    to = "/landing-page/index.html"
    status = 200
    force = true
  
