[functions]
    external_node_modules = ["express"]
    node_bundler = "esbuild"
  
[build]
    functions = "./netlify/functions"
    publish = "src/public"

[[redirects]]
    from = "/"
    to = "/landing-page/index.html"
    status = 200
    force = true

[[redirects]]
    from = "/*"
    to = "https://sub-manager.netlify.app/.netlify/functions/app"
    status = 200
  
