[functions]
    external_node_modules = ["express"]
    node_bundler = "esbuild"
  
[build]
    functions = "netlify/functions"
    publish = "public"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/app"
    status = 200
  
